services:
  gateway:
    build: ./gateway
    restart: always
    ports:
      - 3030:80
  frontend:
    build: ./frontend
    restart: always
    # ports:
    #   - 3040:3000
    volumes:
      - ./frontend/src:/usr/src/app/src
  mongo:
    image: mongo:6.0-focal
    restart: always
    volumes:
      - user-mongodb:/data/db
    environment:
      # MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/user-mongodb-username
      # MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/user-mongodb-password
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hello
    secrets:
      - user-mongodb-username
      - user-mongodb-password
    user-service:
      build: ./user-service
      restart: always
      environment:
        DB_HOST: mongo
        DB_PORT: 27017
        DB_USERNAME_FILE: /run/secrets/mongo-db-username
        DB_PASSWORD_FILE: /run/secrets/mongo-db-password
      volumes:
        - ./user-service/src:/usr/src/app/src
      ports:
        - 4000:80
      secrets:
        - mongo-db-username
        - mongo-db-password
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME_FILE: /run/secrets/user-mongodb-username
  #     ME_CONFIG_MONGODB_ADMINPASSWORD_FILE: /run/secrets/user-mongodb-password
  #     # ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #     ME_CONFIG_BASICAUTH: false
  #   secrets:
  #     - user-mongodb-username
  #     - user-mongodb-password

secrets:
  user-mongodb-username:
    file: ./secrets/user-mongodb-username 
  user-mongodb-password:
    file: ./secrets/user-mongodb-password

volumes:
  user-mongodb:
    
