services:
  gateway:
    build: ./gateway
    restart: always
    ports:
      - 3030:80
  frontend:
    build: ./frontend
    restart: always
    # ports:
    #   - 3040:3000
    volumes:
      - ./frontend/src:/usr/src/app/src
  task-management-service:
    build: ./task-management-service
    restart: always
    environment:
      DB_HOST: task-management-mongo
      DB_PORT: 27017
      DB_USERNAME_FILE: /run/secrets/task-management-mongodb-username
      DB_PASSWORD_FILE: /run/secrets/task-management-mongodb-password
      AUTH_SECRET_KEY_FILE: /run/secrets/auth-secret-key
    volumes:
      - ./task-management-service/src:/usr/src/app/src
    ports:
      - 4000:80
    secrets:
      - task-management-mongodb-username
      - task-management-mongodb-password
      - auth-secret-key

  user-service:
    build: ./user-service
    restart: always
    environment:
      DB_HOST: user-mongo
      DB_PORT: 27017
      DB_USERNAME_FILE: /run/secrets/user-mongodb-username
      DB_PASSWORD_FILE: /run/secrets/user-mongodb-password
      AUTH_SECRET_KEY_FILE: /run/secrets/auth-secret-key
    volumes:
      - ./user-service/src:/usr/src/app/src
    ports:
      - 4000:80
    secrets:
      - user-mongodb-username
      - user-mongodb-password
      - auth-secret-key   
  
  task-management-mongo:
    image: mongo:6.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/task-management-mongodb-username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/task-management-mongodb-password
    volumes:
      - task-management-mongodb:/data/db
    expose:
      - 27017
    secrets:
      - task-management-mongodb-username
      - task-management-mongodb-password

  user-mongo:
    image: mongo:6.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/user-mongodb-username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/user-mongodb-password
    volumes:
      - user-mongodb:/data/db
    expose:
      - 27017
    secrets:
      - user-mongodb-username
      - user-mongodb-password

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8082:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@user-mongo:27017/
  #     ME_CONFIG_BASICAUTH: true
  #     ME_CONFIG_BASICAUTH_USERNAME: admin
  #     ME_CONFIG_BASICAUTH_PASSWORD: example
  #     ME_CONFIG_MONGODB_ENABLE_ADMIN: true

secrets:
  user-user-mongodb-username:
    file: ./secrets/user-mongodb-username
  user-mongodb-password:
    file: ./secrets/user-mongodb-password
  task-management-mongodb-username:
    file: ./secrets/task-management-mongodb-username
  task-management-mongodb-password:
    file: ./secrets/task-management-mongodb-password
  auth-secret-key:
    file: ./secrets/secret.key

volumes:
  user-mongodb:
  task-management-mongodb:
    
