services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/usr/src/app/src
  user-service:
    build: ./user-service
    restart: always
    environment:
      DB_HOST: mongo
      DB_PORT: 27017
      DB_USERNAME_FILE: /run/secrets/mongo-db-username
      DB_PASSWORD_FILE: /run/secrets/mongo-db-password
    volumes:
      - ./user-service/src:/usr/src/app/src
    ports:
      - 4000:80
    secrets:
      - mongo-db-username
      - mongo-db-password
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: /run/secrets/mongo-db-username
      MONGO_INITDB_ROOT_PASSWORD: /run/secrets/mongo-db-password
    secrets:
      - mongo-db-username
      - mongo-db-password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: example
      # ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: true

secrets:
  mongo-db-username:
    file: ./secrets/mongo-db-username
  mongo-db-password:
    file: ./secrets/mongo-db-password