services:
  gateway:
    build: ./gateway
    restart: always
    ports:
      - 3030:80
  frontend:
    build: ./frontend
    restart: always
    # ports:
    #   - 3040:3000
    volumes:
      - ./frontend/src:/usr/src/app/src
  user-service:
    build: ./user-service
    restart: always
    environment:
      DB_HOST: mongo
      DB_PORT: 27017
      DB_USERNAME_FILE: /run/secrets/mongo-db-username
      DB_PASSWORD_FILE: /run/secrets/mongo-db-password
      AUTH_SECRET_KEY_FILE: /run/secrets/auth-secret-key
    volumes:
      - ./user-service/src:/usr/src/app/src
    # ports:
    #   - 4000:80
    secrets:
      - mongo-db-username
      - mongo-db-password
      - auth-secret-key
    expose:
     - 80 
  task-management-service:
    build: ./task-management-service
    restart: always
    environment:
      DB_HOST: mongo
      DB_PORT: 27017
      DB_USERNAME_FILE: /run/secrets/mongo-db-username
      DB_PASSWORD_FILE: /run/secrets/mongo-db-password
    volumes:
      - ./task-management-service/src:/usr/src/app/src
    secrets:
      - mongo-db-username
      - mongo-db-password
    expose:
      - 80
  mongo:
    image: mongo:6.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo-db-username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-db-password
    volumes:
      - user-mongodb:/data/db
    expose:
      - 27017
    secrets:
      - mongo-db-username
      - mongo-db-password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: my_password
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true

secrets:
  mongo-db-username:
    file: ./secrets/user-mongodb-username
  mongo-db-password:
    file: ./secrets/user-mongodb-password
  auth-secret-key:
    file: ./secrets/secret.key

volumes:
  user-mongodb:
    
